version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./hostVideos:/videos
      - ./hostResults:/results
    environment:
      - VIDEO_INPUT_DIR=/videos
      - OUTPUT_DIR=/results
