receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]


#✅ This tells the OpenTelemetry Collector to:

#Receive OTLP data (from your app) via port 4318 (http) or 4317 (grpc)

#Expose the metrics for Prometheus to scrape on port 8889