global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

#✅ This tells Prometheus to scrape metrics from the collector #every 5 seconds.

